### ISSUE TITLE
fails to build with ghc-9.4 (Cabal-3.8) for Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [clinty/cabal-debian#4]
```
Building library for cabal-debian-5.2..                           
[12 of 30] Compiling Debian.Debianize.InputCabal                                                                                    

/var/stackage/work/unpack-dir/unpacked/cabal-debian-5.2-1b72bd436a014fe1a3f9901e5cf04ed67e74f560131760d154b22ec2891e8e3d/src/Debian/
Debianize/InputCabal.hs:23:48: error:
    Module                                                        
    ‘Distribution.PackageDescription.Parsec’                                                                                        
    does not export                                               
    ‘readGenericPackageDescription’                               
   |                                                              
23 | import Distribution.PackageDescription.Parsec (readGenericPackageDescription)                                                  
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
```

**Comment by clinty** [comment]
Fixed by https://github.com/clinty/cabal-debian/commit/eefed54dcff22e8fe948210659e59d063e3ff4da

**Comment by alaendle** [comment]
@clinty - thanks - however in the meantime the dependcies got to old to simply re-enable `cabal-debian`:

```
           ansi-wl-pprint version 1.0.2 found
               - cabal-debian requires >=0.6 && <0.7
           optparse-applicative version 0.18.1.0 found
               - cabal-debian requires >=0.11 && <0.18
```

**Comment by clinty** [comment]
@alaendle I've revised the Hackage metadata on 5.2.2 since it seems to work with the versions you specified

**Comment by alaendle** [comment]
@clinty - Thanks! Works as expected.
